### ISSUE TITLE
Error that stops match

### ISSUE THREAD

**Issue by BarrelRider1616** [Baledin/FlyCasual#1]
This errors appears at some point during the match, usually when the AI player causes collision between its ships; then the game sequence is unable to proceed.
![flycasual x wing error](https://github.com/Baledin/FlyCasual/assets/156916197/0fb08984-05c8-4cf2-9c37-5c2be557f116)

**Comment by Baledin** [comment]
Per reddit.com/u/Sampson_Matt, Flight Leader Ubbel's ability is triggering without a target and has a fix. I've implemented the fix and will build a new release tonight.

**Comment by Baledin** [comment]
The latest release [v2.5.20230908.03](https://github.com/Baledin/FlyCasual/releases/tag/2.5.20230908.03) has a fix for this, please let me know if you encounter the issue again. Thanks
