### ISSUE TITLE
Various Tactical Relay Bugs

### ISSUE THREAD

**Issue by quall3** [Baledin/FlyCasual#10]
** Fly Casual Release Version**
Latest

**Describe the bug**
K2-B4 Tactical Relay:
   Only Allows a Friendly ship at range 0-3 to spend a calculate token if the Relay Carrier does have a Calculate token, and does spend the calculate of the carrier, resulting in a single use per turn only.

    The relay should allow any friendly ship at range 0-3 to spend a calculate token while defending to make the opponent choose to gain a Strain or let the user add 1 evade result.

Kalani:
    If an enemy ship ends its maneuver in the bullseye arc of a friendly ship at range 0-3 it may gain 1 stress to acquire a lock on that ship.
    Doing that however forces the Relay carrier to perform an action on its action bar. This is non optional and sometimes causes the carrier to do a reload action (if a hyena or hmp gunship carrys the relay) which gives tham a disarm and forbids them from shooting. This should not happen. The relay has no effect on the carrier when it triggers.

**Comment by Baledin** [comment]
Kalani's ability wasn't returning the active ship selection to the ship which triggered the ability by moving. I have a fix (3da89d7) for this one ready to go. Still reviewing K2-B4

**Comment by Baledin** [comment]
Resolved K2-B4 (turned out to be quite simple). Fix is in 3bf8731.
