### ISSUE TITLE
Concussion bombs do not allow to place fuse markers

### ISSUE THREAD

**Issue by quall3** [Baledin/FlyCasual#13]
** Fly Casual Release Version**
Latest

**Describe the bug**
When dropping a concussion bomb, you are not asked to place a fuse marker when you also have the delayed fuses opgrade equipped.

**To Reproduce**
1. Drop a Concussion Bomb while also have delayed fuses equipped

**Comment by Baledin** [comment]
Concussion Bombs were missing the appropriate subtype classification. Fixed in commit da4c09d.
