### ISSUE TITLE
BoY Wedge ability triggers with Torps

### ISSUE THREAD

**Issue by Kern0wchris** [Baledin/FlyCasual#17]
** Fly Casual Release Version**
Which version did the bug occur in? Latest

**Describe the bug**
The Wedge Ability occurs when using torpedoes on the BoY version. It should only work on primary and with other friendly ships in the attacker arc. 

**To Reproduce**
Use the BoY version and the ability is always active. 

**Expected behavior**

**Screenshots**

**Platform/Device (please complete the following information):**
 - android 
 -

**Comment by Baledin** [comment]
Fixed in 9cb548f.
