### ISSUE TITLE
Ursa Wren crew

### ISSUE THREAD

**Issue by Kern0wchris** [Baledin/FlyCasual#18]
** Fly Casual Release Version**
Which version did the bug occur in? Latest

**Describe the bug**
Ursa Wren crew isn't there for rebels to select. 

**To Reproduce**
N/A

**Expected behavior**
Should be available and then give the equipped ship the option of taking a lock action (if not stressed or already done a lock action) against any enemy ship in range. 

**Screenshots**

**Platform/Device (please complete the following information):**
 - Android

**Additional context**

**Comment by Baledin** [comment]
Confirmed missing, I'm working on pulling Ursa Wren (as well as others) from the Fly Casual Legacy fork right now. Will update and close with commit when finished.

**Comment by Baledin** [comment]
Commit a8ae1dd. Included with latest release.
