### ISSUE TITLE
Resolving a bomb caused a crash

### ISSUE THREAD

**Issue by hibellm** [Baledin/FlyCasual#2]
Game crashed after a bomb was resolved (happened with seismic charges as well as these proton bombs)

![image](https://github.com/Baledin/FlyCasual/assets/22495646/3dd800d4-dbf8-4ad4-8891-966942d71d00)

**Comment by Baledin** [comment]
I suspect that this happens when there isn't a target being hit. What precipitated the crash?

**Comment by Baledin** [comment]
Can you confirm whether or not a ship was destroyed when the crash happened? Tor Phun's ability shouldn't be triggering without someone getting destroyed first and just wanted to make sure it was triggering as expected.

**Comment by Baledin** [comment]
I've been able to replicate this issue. The error is due to the Tools.IsSameShip check not validating inputs before the check. I'll have a fix in the next release.
