### ISSUE TITLE
SSP Darth Vader (X1) does not have an additional shield

### ISSUE THREAD

**Issue by grandpajive** [Baledin/FlyCasual#20]
** Fly Casual Release Version**
v2.5.20240223.03 (latest release)

**Describe the bug**
Starter Pack Darth Vader has three shields instead of two

**To Reproduce**
Select SSP Darth vader, start game

**Expected behavior**
Vader should have 3 shields

**Screenshots**
![image](https://github.com/Baledin/FlyCasual/assets/6842889/9939bbb6-e30d-458a-a4ba-1437c59481d0)

The UI shield was cut off

**Platform/Device (please complete the following information):**
 - Version Windows 11

**Comment by Baledin** [comment]
SSP shield added (philpurslove). 4b27d76
Noticed BoY missing this extra shield as well, fixed. 794da1d
