### ISSUE TITLE
Tie Reapers do not give you an option to use Controlled Ailerons

### ISSUE THREAD

**Issue by grandpajive** [Baledin/FlyCasual#21]
** Fly Casual Release Version**
Current

**Describe the bug**
Tie Reapers now allow you to choose to perform their boost (which is not an action). The option is not presented to use the ailerons.

**To Reproduce**
Activate your reaper
The aileron option is presented, without a choice to ignore.

**Expected behavior**
An option should presented.

*IF* the aileron fails, the boost returns the ship to its activation position. The dial is then revealed and that is the maneuver the ship executes.

**Platform/Device (please complete the following information):**
Windows 11

**Additional context**
Vizier:
![image](https://github.com/Baledin/FlyCasual/assets/6842889/cfac069b-5daf-46d8-9e33-ca9dd5642bb6)

Vizier would have an option presented to perform an aileron boost. 
If Vizier does perform the the aileron, they would be able to perform is ability (co-ordinate), then reveal their maneuver. No further actions would be allowed (except for an enemy bump-red focus).

However,
If Vizier chooses to try the aileron boost, and fails (bumping into a friendly, enemy, overlapping an obstacle, etc) the boost fails. No damage is suffered, and Vizier is returned to their original position. 
Then, the dial is revealed, and Vizier performs their maneuver.

**Comment by russbean** [comment]
I have experienced the same issue with Captain Feroph.  There is no option to skip the boost, so the player is forced to accept a boost option in order to continue play.  Also, the boost allows the player to land on an obstacle which should not be allowed.  The boost should be cancelled as a result.

**Comment by Baledin** [comment]
The current TIE Reaper doesn't have the correct Ailerons ability (instead having Advanced Ailerons). Need to replace the Advanced Ailerons with Controlled Ailerons.

**Comment by Baledin** [comment]
Fixed, commit 5756535
