### ISSUE TITLE
Missing standard loadouts

### ISSUE THREAD

**Issue by BDMarks** [Baledin/FlyCasual#25]
**Is your feature request related to a problem? Please describe.**
Please add the SLs from the tie bomber expansion pack and Battle Over Endor, for example:
From the TIE/sa Bomber expansion pack: 
- Tomax Bren - Scimitar Veteran
- Deathfire - Obstinate Bomber
From the Battle Over Endor scenario pack
- Scimitar 1 - Battle Over Endor (TIE/sa Bomber)
- Colonel Jendon - Battle Over Endor (TIE/D Defender)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Baledin** [comment]
Added to Roadmap. Closing this comment as duplicate.
