### ISSUE TITLE
Upgrades available in FlyCasualLegacy fork

### ISSUE THREAD

**Issue by grandpajive** [Baledin/FlyCasual#26]
** Fly Casual Release Version**
N/A

**Describe the bug**
There are some ships/upgrades/gunners/talents added to FlyCasualLegacy that are not in your fork

**To Reproduce**
..

**Expected behavior**
Missing ships/pilots:
New YT-2400 + new Outrider title (Rebel/Scum)
Dash Rendar 
Leebo
SL Dash/Leebo for scum (an option to utilize the rebel versions would be nice.. thanks AMG). 

Lin Gaava Tie/FO (First Order)
Agent Tierny Xi Class Shuttle (First Order)

SoC - Republic - All ARCs, Torrents, ETAs. Born for This.

Missing devices:
Electro-Chaff Missiles

Missing crew/gunners:
Crew:
Bo-Katan Kryze (Rebel/Scum)
Bo-Katan Kryze (Republic/Separatist)

Fenn Rau (Rebel/Scum)
Ursa Wren (Rebel)
Captain Hark (Empire)
Gar Saxon (Empire)
Greef Karga (Scum)
Prime Minister Almec (Republic/Scum)
Ahsoka Tano (Republic/Scum)
Maul [two crew slot coordinator] (Scum)
Savage Opress (Scum/Separatist)
Korkie Kryze (Republic)
Obi-Wan Kenobi (Republic)
Satine Kryze (Republic)

Gunner:
Tiber Saxon (Empire)
Gar Saxon (Scum)
Ursa Wren (Republic)

Talent:
Clan Training

**Platform/Device (please complete the following information):**
All

**Additional context**
Hopefully it won't be very difficult to merge this code.

**Comment by Baledin** [comment]
Fantastic, I'll check these out. Thanks!

**Comment by Baledin** [comment]
Closing as these are now included in the roadmap and will have individual issues as we work on each item.
