### ISSUE TITLE
XWS Import issue - Cad Bane

### ISSUE THREAD

**Issue by grandpajive** [Baledin/FlyCasual#27]
** Fly Casual Release Version**
Current

**Describe the bug**
Fly Casual fails to Import Cad Bane (scum) via XWS format (via YASB and LBN) 

XWS String for Cad Bane (scum) 

Cad Bane [Scum]
[{"id":"cadbane","name":"cadbane","points":4,"ship":"rogueclassstarfighter"}]

**Expected behavior**
Chad Bane appears in your squad.

**Comment by Baledin** [comment]
I'll see if I can get "Chad" Bane to appear :D

**Comment by Baledin** [comment]
Fixed, commit 66db6b3.
