### ISSUE TITLE
Palpatine Crew gets asked to use even if no Eyeball Result

### ISSUE THREAD

**Issue by quall3** [Baledin/FlyCasual#28]
** Fly Casual Release Version**
current

**Describe the bug**
When a ship rolls dice, it gets asked to use the Emperor Palpatine Abillity, even if the dice dont show any eyeball result.

**To Reproduce**
1. Have EMperor Palpatine crew in your list
2. Roll dice with another ship than the one Carrying Palpatine Crew
3. Do not roll Eyeball Results
4. You are asked to spend the palpatine force with no effect other than wasting the force.
5. The AI always spends the Force on first occasion, which is somewhat annoying.

**Expected behavior**
Only allow Palpatine Crew to be Spent when Dice results show an eyeball, similar to Focus, Calculate or Natural Force.

**Comment by Baledin** [comment]
Added limit on when this modification appears to only show when at least one Eyeball has been rolled. Commit 87a66f6.
