### ISSUE TITLE
Aurora sing pilot ability error

### ISSUE THREAD

**Issue by lumbduck** [Baledin/FlyCasual#29]
** Fly Casual Release Version**
Latest (2.5.20240223.03)

**Describe the bug**
When transferring a stress token using Aurora Sing's (firespray, separatist) pilot ability, the game threw an index error.

**To Reproduce**
This error has not been reproduced yet, as this was my first time using Aurora Sing's ability. I will provide as much context as I can.
1. Start Aurora's engagement as the player character (in this case, AI opponent had completed all of their engagements).
2. When prompted, elect to use Aurora pilot ability (swap orange/red tokens between two enemies at range 1)
3. Select enemy ships (in this case, Vader TIE Advanced with no orange/red tokens and Seyn fighter with 1 stress token)
4. At next prompt, elect to transfer the stress token to Vader
5. ArgumentOutOfRange exception is thrown (see screenshot)

**Expected behavior**
After transferring the stress token, the engagement should have moved forward to Aurora's attack

**Screenshots**
Error message:
![Screenshot 2024-06-03 at 1 23 18 PM](https://github.com/Baledin/FlyCasual/assets/1512923/5f4a16bf-0a4b-4587-861e-522696c4f685)

Context showing ship layout (Aurora highlighted, Vader at top, and Seyn at bottom in red TIE fighter):
![Screenshot 2024-06-03 at 1 23 53 PM](https://github.com/Baledin/FlyCasual/assets/1512923/c02e7d15-8d30-47f5-994c-83b22682dded)

**Platform/Device (please complete the following information):**
 - OS: MacOS Sonoma 14.5 (23F79)
 - Hardware: Macbook Pro 13 inch (2018) with 2.7 GHz Quad-Core Intel Core i7, Intel Iris Plus Graphics 655 1536 MB, and 16 GB 2133 MHz LPDDR3 RAM

**Additional context**
After throwing the exception, the stress token appears to have been correctly transferred (visible in the side bar), but the app accepts no more input other than erroneously allowing you to select and deselect enemies for the Aurora pilot ability (no way to submit, cancel, or otherwise progress the game).

**Comment by lumbduck** [comment]
I was able to confirm the exact same error message in a different context, so it should be reproducible simply by executing Aurra* Sing's pilot ability (* sorry for the autocorrected spellings)

**Comment by Baledin** [comment]
There was an issue handling ships with no tokens as well as potentially re-handling tokens already moved. I've reworked the handling of ships and tokens, including now throwing an error if you select two ships and there are no applicable tokens to transfer. Commi 1eb6766.
