### ISSUE TITLE
Latest version won't open (MacOS 13.6.3, M1Max)

### ISSUE THREAD

**Issue by HrPating** [Baledin/FlyCasual#3]
** Fly Casual Release Version**
Version 2.5 - 20230908.03

**Describe the bug**
After doing the chmod +x *  in terminal, the program tries to open, but then gets error "File is damaged and can't be opened". Tried to download again several times, same thing occurs. version 20230908.02 works fine. 

**To Reproduce**
Download latest version
Move it to apps-folder
Open terminal av MacOS-folder and type chmod +x *
Try to open Fly Casual

**Expected behavior**
The program launching

**Screenshots**
<img width="260" alt="Skjermbilde 2024-01-30 kl  11 23 19" src="https://github.com/Baledin/FlyCasual/assets/158155152/e792cf31-b432-4b83-835c-26636da6219d">

It's in Norwegian, but ut says "FlyCasual" is damaged and can't be opened. You should move it to trash.

**Platform/Device (please complete the following information):**
 - OS: MacOS 13.6.3, MacBook Pro M1Max

**Comment by Baledin** [comment]
Just to confirm, this was newly downloaded, correct? There was a known build issue with the original file but a new file had been loaded about a week ago. 

Also, to clarify since it's not in the Steps to Reproduce above, you unzipped the contents and moved just the FlyCasual.app to the apps folder? I'm guessing yes as the error message says FlyCasual and not the filename of the zip.

**Comment by HrPating** [comment]
This was downloaded 9 hours ago. Right before I wrote the issue.
Yes, I unzipped it and moved the FlyCasual.app to the apps folder before doing the terminal thing. (Sorry for not being clear)

**Comment by Baledin** [comment]
You're good, I just wanted to make sure. Thanks for confirming. I'll take a peek at the build options, I don't believe anything had changed between .02 and .03 as far as how I built them.

**Comment by Baledin** [comment]
Have you followed the steps in the txt file included? Researching, MacOS isn't helpful with their error messages and one reason can be returned from the file not being signed (it will never be, I don't own a mac / Apple Dev account to sign the files with).

**Comment by Baledin** [comment]
An alternative workaround to the signing issue (which chmod +x * is supposed to get around) is to use the following:
`execute "xattr -cr <path to build>"`

**Comment by HrPating** [comment]
I made it work:
Opening a terminal window. Writing: sudo chmod -R 755 /Applications/FlyCasual.app
App opens and works fine

I googled your last suggestion after not making it work and got here: https://issuetracker.unity3d.com/issues/macos-build-is-damaged-and-cannot-be-opened-error-when-downloading-unity-build-from-internet

**Comment by Baledin** [comment]
I'm glad it worked! I was about to send you a zip with a rebuild to see if doing a clean build fixes it. Any suggestions for the txt file to help others is greatly appreciated.

MacOS is the only OS that I do not have a test bed to work with here so I'm a little in the dark trying to fix these issues.

**Comment by HrPating** [comment]
Edited the readme.txt with the command that worked for me. Just to be clear, all earlier builds have worked for me with just using the first command (chmod +x *). So I don't know what the problem is. I know nothing about unity :/

[Readme.txt](https://github.com/Baledin/FlyCasual/files/14104165/Readme.txt)

**Comment by Baledin** [comment]
Thanks, I'll upload a new copy of the file with an update to the Readme. The only difference that I see is the sudo which makes me think it's a permissions issue with running chmod on the file (the numbers vs +x just explicitly describe the read/write/execute permissions--sudo let's it happen if you didn't already have permissions to do it).

This is less of a Unity issue and more of a MacOS security making it hard to run non-App Store approved items.

**Comment by Baledin** [comment]
I'll update the Readme.txt file for the MacOS download. This looks like it's a permissions issue when trying to execute the application in MacOS (not a build issue). Apple doesn't like non-AppStore applications and makes it very hard to run them. Thanks for your work on this!
