### ISSUE TITLE
Game crashes upon destruction of vader in his tie defender

### ISSUE THREAD

**Issue by mbradyneeley** [Baledin/FlyCasual#30]
** Fly Casual Release Version**
Which version did the bug occur in?
202309
**Describe the bug**
I have noticed this happen now a few times in a row. I am playing scum with a firespray and two fang fighters against vader in the tie defender and two other tie interceptors. Each time vader is destroyed, I get a bug and the game crashes. Here is the screenshot of the error.
**To Reproduce**
Local vs AI. Destroy vader with primary attack.

**Expected behavior**
Game continues, vader explodes

**Screenshots**
![image](https://github.com/Baledin/FlyCasual/assets/55114836/c7ae5254-fd3e-4387-8fea-823e2616f2e2)
https://www.reddit.com/r/XWingTMG/comments/199i7og/comment/l809vvd/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
**Platform/Device (please complete the following information):**
 - OS: [e.g. Windows, Mac, Android]
 - Version [e.g. Windows 10, iOS22]

**Additional context**

**Comment by philpursglove** [comment]
I've tried to reproduce this tonight but every time Darth Vader dies the game continues as normal for me.

**Comment by philpursglove** [comment]
I've tried this again tonight, still can't repro it. I'm closing it _for now_, happy to reopen and investigate again if it crops up again.
