### ISSUE TITLE
Tycho cannot perform Jake Farrell's free focus when stressed

### ISSUE THREAD

**Issue by lumbduck** [Baledin/FlyCasual#31]
** Fly Casual Release Version**
Latest 2.5.20240223.03

**Describe the bug**
Jake Farrell's (A-Wing) pilot ability can provide a free focus action to another ship. When Tycho Celchu (A-Wing) is stressed, they should still be able to perform this focus action as per their own pilot ability. This is not the case.

**To Reproduce**
1. Start a game with a squad containing 2 A-wings piloted by Jake Farrell and Tycho Celchu.
2. Use the first round to stress Tycho while keeping Jake behind Tycho near Range 1.
3. In the next round, fly Jakes's maneuver to him within Range 1 of Tycho, ideally either in front or behind with room for reposition.
4. During Jake's perform action step, perform a successful reposition ending within Range 1 of Tycho.
5. On trigger of Jake's pilot ability, attempt to give free action to Tycho. Action will not be granted.

**Expected behavior**
Expect Tycho to be able to perform a focus action as per Tycho's pilot ability, since Tycho has fewer than 3 stress tokens.

**Screenshots**

**Platform/Device (please complete the following information):**
 - MacOS
 - Sonoma 14.5

**Additional context**
I cannot find a ruling on this, but it appears it should be true for both rules-as-written and rules-as-intended.

**Comment by Baledin** [comment]
I'm having trouble replicating this. The one instance where I had an issue was actually correct--I had an Evade Action triggered before Jake's action tried to give me another one.

Note, this is really tough to test in isolation, I'm having troubles giving an A-Wing enough stress (doable, but each test is 30~ min, miss a step I have to start over).

Can you provide some concrete examples of when this is failing? I'll keep testing as I work through other bugs.

**Comment by lumbduck** [comment]
It did happen repeatedly at the time, but I can't reproduce it now either. I have several versions of the list to try again, including one that had custom Gina who might have interacted weirdly. I'll close for now and let you know if I can replicate again.
