### ISSUE TITLE
Contingency Protocol bug

### ISSUE THREAD

**Issue by quall3** [Baledin/FlyCasual#32]
** Fly Casual Release Version**
Latest

**Describe the bug**
When Contingency Protocol (CP) triggers, all ships with Contingency Protocol are allowed to do an action. 

**To Reproduce**
1. Play some droids with the Contingency Protocol upgrade
2. Have 1 of them destroyed
4. The destroyed ship and all other ships are allowed to do an action

**Expected behavior**
Card text says "Another ship" is allowed to do an action. 
That means upon being destroyed, you choose 1 OTHER ship with the CP upgrade. That ship may perform an action, even while stressed.

**Comment by Baledin** [comment]
Updated Contingency Protocol to be triggered from destroyed ship to simplify ability. Commit 8dbd256.
