### ISSUE TITLE
Latest fly casual download issue

### ISSUE THREAD

**Issue by Kern0wchris** [Baledin/FlyCasual#33]
Have a Google Pixel 7a running android. 

It installs the 2.4 64bit android download, but won't install the 2.5 android download. 

Help please!

**Comment by Baledin** [comment]
Apologies for not getting back to this, somehow I missed your message (I believe we were on family vacation and never got back to it, again, apologies).

I'm not sure what you mean by 2.4 64bit version, as I haven't released any 2.4. If you have the original FlyCasual installed as released by Sandrem, you will need to uninstall it before installing this new version.

**Comment by Baledin** [comment]
Closing this issue as no response in over two months.
