### ISSUE TITLE
E-Wing Corran Horn 

### ISSUE THREAD

**Issue by BD1-buntu** [Baledin/FlyCasual#34]
** Fly Casual Release Version**
Version 2.5 - 2.5.20240223.03
**Describe the bug**
Game crashes when using Corran Horn in an E-Wing.

**Platform/Device (please complete the following information):**
 - OS: Android
 - Version: 14

**Comment by Baledin** [comment]
Can you provide any additional details? Is it crashing before you get into the match? Is it crashing when you make an attack?

**Comment by BD1-buntu** [comment]
It crashed before a match.
![Screenshot_2024-06-30-15-01-31-63_6a9a0e13d399c33090469690285dbc55](https://github.com/Baledin/FlyCasual/assets/174265863/38983f04-90b3-48f4-bbfa-4e7e2bfdc3a5)

**Comment by Baledin** [comment]
That helps immensely. Thanks!

**Comment by Arc106** [comment]
I also had the same problem, match won't start when he is one of the pilots in a list, but my error text looks different. Not sure if it helps or not
![Cannot use Corran Horn E-Wing](https://github.com/Baledin/FlyCasual/assets/174386579/1bc7c4dd-319b-476b-b852-459c3d282759)

**Comment by Baledin** [comment]
Thank you for sharing, it's ultimately the same error. Apparently the class constructor got dropped. I haven't had the time to dig into it in detail but should be easy to fix.

I'm honestly shocked I haven't seen this, I love E-Wings.

**Comment by Baledin** [comment]
Missed including this in the last release. Commit 3c68f60
