### ISSUE TITLE
Add Battle over Endor quick builds

### ISSUE THREAD

**Issue by whittaker007** [Baledin/FlyCasual#35]
**Is your feature request related to a problem? Please describe.**
The quick builds for the Battle over Endor scenario pack are missing

**Describe the solution you'd like**
Please add these pilots

**Additional context**
[Battle Over Endor Scenario Pack](https://xwing-miniatures-second-edition.fandom.com/wiki/Battle_Over_Endor_Scenario_Pack)

**Comment by Baledin** [comment]
Not to be pedantic, but there are quick builds in the game but I assume that you mean Standard Loadout pilots?

**Comment by whittaker007** [comment]
Yes, standard loadout pilots sorry. Battle over Endor does not contain quick builds.

**Comment by Baledin** [comment]
Added as individual items to the roadmap. Closing this issue.
