### ISSUE TITLE
Will Epic rules be added at some point?

### ISSUE THREAD

**Issue by LordSkritch** [Baledin/FlyCasual#38]
Love the work put into this game.
I was wondering if there were any plans for Epic Ships at some point or perhaps as a forked project.

**Comment by Baledin** [comment]
I would absolutely love to add Epic. There are other priorities currently but it's on the roadmap (I'll be posting that here soon).

**Comment by Baledin** [comment]
Added to roadmap, closing this issue as we will be tracking through the roadmap itself.
