### ISSUE TITLE
ST-70 Assault Ship missing Razorcrest ship title

### ISSUE THREAD

**Issue by jones-roman3** [Baledin/FlyCasual#4]
** Fly Casual Release Version**
Which version did the bug occur in?

v2.5.20240223.01-Windows

**Describe the bug**

When building a Scum list with Din Djarin in the ST-70 Assault Ship, the Razor Crest upgrade was not available.

Also could not find Clan Training under talents

**To Reproduce**
1. Start making a new scum list
2. Add the ST-70
3. Select Din Djarin as the pilot
4. Go to loadout for the ST-70
5. Click talents
6. See "Clan Training" is not available
7. Go Back
8. Click Title
9. No upgrades are available

**Expected behavior**

Expect to see missing upgrades

**Screenshots**

Talent screen for ST-70
![image](https://github.com/Baledin/FlyCasual/assets/32491852/f4ca7c3a-8038-4b1d-9a61-26341e2b917a)

Title screen for ST-70
![image](https://github.com/Baledin/FlyCasual/assets/32491852/bcfcca5c-fade-4cb4-a8e3-85222349ea84)

**Platform/Device (please complete the following information):**
 - OS: Windows
 - Version Windows 10

**Additional context**

**Comment by Baledin** [comment]
It appears that the ship was added but the title never was. Marking this as a (missing) feature request instead of a bug.

**Comment by grandpajive** [comment]
note: code available from FlyCasualLegacy fork

**Comment by Baledin** [comment]
Razor Crest title added--commit 67abdeb.

**Comment by Baledin** [comment]
Clan Training imported by @philpursglove, commit e5f6af5 (see issue #44)
