### ISSUE TITLE
Vagabond in Tie Striker ability not working

### ISSUE THREAD

**Issue by BDMarks** [Baledin/FlyCasual#43]
**Fly Casual Release Version**
Version 2.5 - 2.5.20240906.01

**Online Game Mode**
No

**Describe the bug**
Vagabond in the Tie Striker's ability is to drop a device after using the adaptive ailerons. However, after the aileron maneuver, there is no choice to drop a device, instead, the dial maneuver is immediately performed

**To Reproduce**
Load out Vagabond with a device/bomb.
Perform the aileron maneuver

**Expected behavior**
After perforrning the aileron maneuver, expect to see a prompt to drop a device or skip.

**Screenshots**

**Platform/Device (please complete the following information):**
 - OS: Android
 - Version [e.g. Windows 10, iOS22] - not sure, tablet is at home

**Additional context**

**Comment by Baledin** [comment]
The pilot ability was there and "worked" but never linked correctly to Vagabond. Commit 81caa25.
