### ISSUE TITLE
Arvel (rebel rz1 awing) and oicann (imperial decimator) cannot modify dice at range 0

### ISSUE THREAD

**Issue by grandpajive** [Baledin/FlyCasual#46]
**Fly Casual Release Version**
Current 
**Online Game Mode**
No

**Describe the bug**
Arvel and Oicann *must* treat range 0 as a range 1 attack. 

**To Reproduce**
1. Get arvel/Oicann to r0
2. Shoot
3. Arvel has 2 dice and cannot modify. Oicann has 3 dice and cannot modify.
 

**Expected behavior**
Arvel should throw three red dice and spend a focus/lock etc
Oicann should have 4 red dice and can modify the results

**Screenshots**
None

**Platform/Device (please complete the following information):**
Windows current 
**Additional context**

**Comment by Baledin** [comment]
Minimum weapon range was being changed instead of modifying the actual range of the attack. I've updated the check to modify the actual range so it will be treated as a normal Range 1 attack while at Range 0. Commit 4839044.
