### ISSUE TITLE
Scum Rogue Class fighter has a 4k turn instead of a 5k turn on the dial

### ISSUE THREAD

**Issue by Rinzler2o** [Baledin/FlyCasual#5]
** Fly Casual Release Version**
all so far, including current.

the scum rogue class fighter, and maybe the CIS one as well, has an incorrect dial. The 4 k-turn should be replaced with a 5 k-turn. Thank you!

**Comment by Baledin** [comment]
Confirmed wrong maneuver. I have a fix for this ready for the next release.
