### ISSUE TITLE
Beskar reinforced plating charges are not spent

### ISSUE THREAD

**Issue by MUGNERCL** [Baledin/FlyCasual#53]
**Fly Casual Release Version**
FlyCasual-v2.5.20240906.01-Windows

**Online Game Mode**
No

**Describe the bug**
I had Joy Rekkoff with Beskar Plating (and Ion Missile). My ship received 2 criticals. Both times i was offered the chance to discard the critical completely.  This choice should cost 2 charges. I accepted both times.
Opposite ship was a Tie-Silencer.

I will test further to see if this only happens when 2 criticals are received.

**Expected behavior**
The second time should have not be possible because it costs 2 charges to do so once. Additionaly, at the end of the engagement, the charge count was still 2. 

**Screenshots**

**Platform/Device (please complete the following information):**
Windows 11

**Comment by MUGNERCL** [comment]
The bug can be re-reproduced when receiving only 1 critical.

**Comment by Baledin** [comment]
It appears that Beskar is using charges from the host ship instead of the upgrade. Fixed in commit 6539bd8.
