### ISSUE TITLE
Cannot use Joy Rekkoff's ability 

### ISSUE THREAD

**Issue by MUGNERCL** [Baledin/FlyCasual#54]
**Fly Casual Release Version**
FlyCasual-v2.5.20240906.01-Windows

**Online Game Mode**
No

**Describe the bug**
Joy Rekkof's ability allows him to spend a charge on a equipped missible (Here Ion Missile) to reduce by one the count of green die the opponent will have. The game does not offer to use this ability.

**To Reproduce**
Equip Joy Rekkof with Ion Missile and perform an attack.

**Expected behavior**
A pop-up should offer the player to use that ability.

**Comment by Baledin** [comment]
Joy's ability is usable with Torpedos (and works fine when tested), not missiles. Closing issue.
