### ISSUE TITLE
Error and images not displayed when setting an avatar.

### ISSUE THREAD

**Issue by russbean** [Baledin/FlyCasual#6]
** Fly Casual Release Version**
I have experienced this issue on Windows 11 and Android

**Describe the bug**
When setting or changing the player's avatar an error message is displayed on the "All" tab.  Dismiss the error and a loading message is displayed and hangs.  The loading message goes away if the user selects the Rebellion faction. When the user chooses the Imperial faction a similar or the same error is displayed.  Only one icon displays for selection. None of the other faction menus have this error. If repeated too many times the game will freeze.

**To Reproduce**
1. Go to 'OPTIONS'
2. Click on the AVATAR image to change it
3. Also try the 'IMPERIALS' menu

**Expected behavior**
Display a complete list of avatar icons for the user to select.

**Screenshots**
![Screenshot (8)](https://github.com/Baledin/FlyCasual/assets/27082671/9e145d95-ff40-4087-83fd-c5e891985bde)

**Platform/Device (please complete the following information):**
 - Windows 11 22H2
 - Android 14

**Additional context**

**Comment by Baledin** [comment]
Error was due to a new image provided for Agent Kallus. While researching the issue, it was apparent that a number of Avatars were not displaying correctly and these will be fixed in the next release.
