### ISSUE TITLE
Add preMade squad for IA

### ISSUE THREAD

**Issue by MUGNERCL** [Baledin/FlyCasual#62]
**Is your feature request related to a problem? Please describe.**
In this fork, the premade squad that can be selected for the AI are not available. They existed in the original Sandrem version. They also exist in the Legacy branch.

**Describe the solution you'd like**
A set of premade squad the AI could use. Obviously mostly ships without complicated upgrade as the AI does not use them.

**Comment by Baledin** [comment]
Sandrem had disabled them while reworking for 2.5 and I haven't taken the time (yet) to review how these were previously implemented. Added to roadmap (#39) and closing issue.
