### ISSUE TITLE
Hol Okand SL has the wrong Initiative

### ISSUE THREAD

**Issue by tampermagnitude** [Baledin/FlyCasual#66]
**Fly Casual Release Version**
Current, but has been apparent for several versions

**Describe the bug**
Hol Okand Rebel Y-wing Standard Loadout has an Initiative of 2 in the game when it should be 4 as per the card.

**To Reproduce**
N/A

**Expected behavior**
Should be changed to be I4

**Platform/Device (be as specific as possible):**
Windows 10 PC

**Comment by Baledin** [comment]
Fixed. Commit 7c95c78.
