### ISSUE TITLE
Can't Open stable-2.5 on MacOS 15.1

### ISSUE THREAD

**Issue by Juanflaco** [Baledin/FlyCasual#70]
**Fly Casual Release Version**
Stable-2.5

**Online Game Mode**
No

**Describe the bug**
On McOS I typically need to modify permissions in the package and then allow the app in security settings. This works with previous versions but for style-2.5 I get a different message when launching it (“FlyCasual” is damaged and can’t be opened) and I don't have the option to allow it in the security settings.

**To Reproduce**
Steps to reproduce the behavior on MacOS 15.1.1:
1. Download FlyCasual and drag app to applications folder
2. Show package contents and open a terminal at MaacOS folder
3. chmod +x *
4. Option-right-click app and choose open
5. Error message indicates FlyCasual is damaged and should be moved to the trash

**Expected behavior**
App should appear in the list of recently opened apps that are eligible for security override.

**Screenshots**

**Platform/Device (be as specific as possible):**
 - OS: Mac
 - Version: 15.1.1

**Additional context**
Can download and launch previous versions without issue

**Comment by Baledin** [comment]
You say Stable 2.5 which is a repo tag, not a release. Did you go to the Releases page and download the MacOS version there? The version would be after Version 2.5 - xxxxxxxxxxx (note, the version will have the date of the point release included, followed by a minor version).

Assuming you are using a release, the files are zipped with instructions. It sounds like you've done some version of the instructions but your listed steps are not quite the same so I'm unsure if the steps you're following match up (I'm not a Mac guy and do not have access to one to test with).

**Comment by Juanflaco** [comment]
Sorry my report wasn't clearer, lemme try this again...

1. I download 2.5 - 20241101.01
2. I follow the instructions in the readme, below are my observations...
If you use MacOS Catalina or later and cannot launch this app bacause it is "3rd-party" or reporting as "damaged," try this:

    The "FlyCasual.app" needs to be in your Applications folder
    Using Finder, navigate to location of "FlyCasual.app" file.
    Right-click on "FlyCasual.app" and choose "Show Package Contents"
    Navigate down to Contents>MacOS, you should see a single file named "Fly Casual" that is identified as a Text document. Right-click on the "MacOS" folder and choose "New Terminal at Folder".
    At the command line in the newly opened Terminal window, type the following: sudo chmod -R 755 *
    Enter your password when prompted
    Go back to the FlyCasual.app file, Ctrl+click on it and choose Open, and then Open again.
**at this stage I'm not prompted to click "open" a second time, as I have been in previous versions. Instead I receive a new message saying the app is damaged and I can cancel or move to trash. I click cancel**

Maybe you also will need to go to "System Preferences / Security / General" and to allow "Fly Casual"
**This step doesn't work because the app was not identified as a security risk (unknown developer) so it doesn't appear in the list of apps you can manually allow to run. It appears as through there's some kind of package issue, separate from the "usual" unknown developer installation issue that the readme corrects.**

Note: I tried previous versions and 2.5.20240223.03 is the most recent one that launches as expected, using the instructions above.

Thanks for looking into this - really appreciate you continuing development on the app!

**Comment by Baledin** [comment]
Thank you for the additional information, can never be sure on the technical level of the individual. I especially appreciate the last known working version. I'll review what has been done differently and see if I can get it working. As mentioned, I don't have a mac so I may need to do a build, have you test it, rinse and repeat.

**Comment by Juanflaco** [comment]
Thanks! Happy to help with testing.On Nov 28, 2024, at 12:06 PM, Jeremy S. ***@***.***> wrote:﻿
Thank you for the additional information, can never be sure on the technical level of the individual. I especially appreciate the last known working version. I'll review what has been done differently and see if I can get it working. As mentioned, I don't have a mac so I may need to do a build, have you test it, rinse and repeat.

**Comment by Baledin** [comment]
@Juanflaco I'm doing a full release tonight and will post a MacOS version. Please let me know if it works for you?

**Comment by Juanflaco** [comment]
Downloaded the latest version (20241101.02) and followed the readme, still received a prompt indicating that the application was damaged and should be moved to trash. I then cleared all attributes using "xattr -cr /Applications/FlyCasual.app" and now it launches without issue.

**Comment by Baledin** [comment]
I believe that this is all a function of the app not being installed through the app store. I just wish it wasn't so difficult for MacOS users. As for the error with previous builds, somehow the Architecture had been reset to "Intel64" instead of "Intel64 + Apple Silicon."
