### ISSUE TITLE
Can't open in MacOs Sonoma 14.6.1

### ISSUE THREAD

**Issue by MrBlankCL** [Baledin/FlyCasual#74]
**Fly Casual Release Version**
Which version did the bug occur in?

FlyCasual-v2.5.20241101.02-MacOS

**Online Game Mode**
Yes/No
NO

**Describe the bug**

Can't install, despite following steps in the readme.txt
System returns this message:
<img width="318" alt="image" src="https://github.com/user-attachments/assets/9e41cc61-85b2-4dca-ab1c-278960a29f17">

**To Reproduce**

**Expected behavior**
Open and run the app
**Screenshots**
<img width="318" alt="image" src="https://github.com/user-attachments/assets/9e41cc61-85b2-4dca-ab1c-278960a29f17">

**Platform/Device (be as specific as possible):**
 - OS: [e.g. Windows, Mac, Android]
 - Version [e.g. Windows 10, iOS22]

MacOs Sonoma 14.6.1

**Additional context**

**Comment by Baledin** [comment]
Please follow the original instructions that came with the zip and while you still have the terminal window open, tppe "xattr -cr /Applications/FlyCasual.app". Then ctrl+click and select open twice, see if that works.

**Comment by MrBlankCL** [comment]
Works fine! Thanks a lot to you all!
