### ISSUE TITLE
Fly Casual.exe system error Windows

### ISSUE THREAD

**Issue by SteveHulin** [Baledin/FlyCasual#76]
**Fly Casual Release Version**
FlyCasual-v2.5.20241101.02-Windows

**Online Game Mode**
No

**Describe the bug**
After extracting the data from the zip file and trying to run Fly Casual.exe, getting the following error:\
The code execution cannot proceed because UnityPlayer.dll was not found. Reinstalling the program may fix this problem.

**To Reproduce**
1. Go to Fly Casual folder
2. Click on Fly Casual.exe
3. See error

**Expected behavior**
Game to start

**Screenshots**
![image](https://github.com/user-attachments/assets/ad2286ec-f458-4066-900b-b5b975748ec0)

**Platform/Device (be as specific as possible):**
 - OS: Windows 11
 - Version 23H2

**Additional context**

**Comment by Baledin** [comment]
Confirmed, I missed adding the .dll to the zip file (It does exist in my build however). I've uploaded a new copy--please re-download and unzip. Let me know if it doesn't work. Thanks!
