### ISSUE TITLE
Clone Z-95s w/ Incorrect Pilot Initiative Value

### ISSUE THREAD

**Issue by Obi-BenKenobi** [Baledin/FlyCasual#84]
![Screenshot_20241203_144514_Fly Casual](https://github.com/user-attachments/assets/5fc0ceda-199e-40e7-a35e-a9534fc0b005)
![Screenshot_20241203_154250_Fly Casual](https://github.com/user-attachments/assets/ef84f568-6a22-4d1c-94ff-737c197e356b)
**Fly Casual Release Version**
V2.5.20241102.02

**Online Game Mode**
No

**Describe the bug**
The 7th Sky Core Pilots in the Clone Z-95 Headhunters are falsely set to pilot initiative 3 (for activation/engagement & it's on their bases).

**To Reproduce**
1. Fly "7th Sky Core Pilots" in the Clone Z-95 Headhunters.

**Expected behavior**
- the 7th Sky Core Pilots in the Clone Z-95 Headhunters should be at pilot initiative 2.

**Screenshots**
Attached

**Platform/Device (be as specific as possible):**
 - OS: Android
 - Version 14

**Comment by Baledin** [comment]
Confirmed wrong initiaive.
