### ISSUE TITLE
"Warthog" Z-95 Non-functional Ability

### ISSUE THREAD

**Issue by Obi-BenKenobi** [Baledin/FlyCasual#85]
![Screenshot_20241206_003059_Launch Bay Next](https://github.com/user-attachments/assets/bb6339ef-41b2-4739-9263-63ae4c92f581)
**Fly Casual Release Version**
V2.5.20241102.02

**Online Game Mode**
No

**Describe the bug**
"Warthog" flown in the Z-95 Headhunter does not have  functioning ability. He should be able to keep himself and friendly non-limited ships from being removed until the end of the engagement phase (so that they can still attack).

**To Reproduce**
1. Fly "Warthog" in the Clone Z-95 Headhunter.
2. Have "Warthog" be destroyed during the engagement phase (before he has the opportunity to attack).
OR
Have a non-limited friendly ship at range 0-2 of "Warthog" be destroyed (for my testing, "Warthog" was flying with 7th Sky Corps Pilots).

**Expected behavior**
- "Warthog" and friendly non-limited ships at range 0-2 should be able to attack during the engagement phase, even after being destroyed. They should not be removed until the end of the engagement phase.

**Platform/Device (be as specific as possible):**
 - OS: Android
 - Version 14

**Additional Context**
- Bug was not tested with the LAAT version of "Warthog". Verification if his ability functions across both chassis my be warranted.

**Comment by Baledin** [comment]
Warthog has the wrong ability assigned. LAAT appears to have the correct Warthog ability which is the same, will relink. Thanks for finding this.
