### ISSUE TITLE
Unable to Update - Pixel 8 Pro Android 14

### ISSUE THREAD

**Issue by Eschguy** [Baledin/FlyCasual#9]
** Fly Casual Release Version**
2.5.20240223.02

**Describe the bug**
When attempting to upgrade by Obtainium or by direct APK download, an "Incompatible" error gets thrown. 

**To Reproduce**
1. Download APK
2. Open file browser and attempt to upgrade
3. Click "Update" when prompted

**Expected behavior**
An update to the latest occurs

**Screenshots**
![Screenshot_20240311-120234](https://github.com/Baledin/FlyCasual/assets/8880292/6976474e-250b-4e03-b430-9c65c0b0e302)
![Screenshot_20240311-120139](https://github.com/Baledin/FlyCasual/assets/8880292/43e4bc22-d189-4886-9bd9-722b12156b5a)

**Platform/Device (please complete the following information):**
 - OS: Android 14
 - Version UQ1A.240205.004

**Comment by Baledin** [comment]
I've heard other reports of this, it's generally due to having an older version installed. Can you check if you have an older version of Fly Casual installed. If so, uninstall it then try the new version again?

**Comment by Baledin** [comment]
I've rebuilt the Android APK with some different options. I tried on my own Pixel Pro and it updated (no need to uninstall) just fine. Try redownloading and trying again.

**Comment by Eschguy** [comment]
Still didn't work, though uninstalling/installing did work.

**Comment by Baledin** [comment]
Interesting, oddly the old file wouldn't work with uninstalling/reinstalling but the new file allowed an in-place upgrade. Thanks Android for being so consistent! lol

Closing this one as you're working. I'll keep monitoring things to improve my build process and hopefully these wrinkles will go away.
